-- Setup script for EDITION_USER with Edition-Based Redefinition support
-- Run as SYSTEM user

-- Create the user
CREATE USER EDITION_USER IDENTIFIED BY EDITION_USER
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

-- Grant basic privileges
GRANT CONNECT, RESOURCE TO EDITION_USER;
GRANT CREATE SESSION TO EDITION_USER;
GRANT CREATE TABLE TO EDITION_USER;
GRANT CREATE SEQUENCE TO EDITION_USER;
GRANT CREATE PROCEDURE TO EDITION_USER;
GRANT CREATE VIEW TO EDITION_USER;

-- Enable the user for editions
ALTER USER EDITION_USER ENABLE EDITIONS;

-- Create editions (if they don't exist)
BEGIN
  EXECUTE IMMEDIATE 'CREATE EDITION V1 AS CHILD OF ORA$BASE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -38801 THEN NULL; -- edition already exists
    ELSE RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE EDITION V2 AS CHILD OF V1';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -38801 THEN NULL; -- edition already exists
    ELSE RAISE;
    END IF;
END;
/

-- Grant USE on editions to the user
GRANT USE ON EDITION V1 TO EDITION_USER;
GRANT USE ON EDITION V2 TO EDITION_USER;

-- Verify setup
SELECT 'Editions available:' AS info FROM DUAL;
SELECT edition_name FROM all_editions ORDER BY edition_name;

SELECT 'User editions enabled:' AS info FROM DUAL;
SELECT username, editions_enabled FROM all_users WHERE username = 'EDITION_USER';

COMMIT;
